#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        cgs
# Description: Checks the git statuses of given git repositories. By default,
#              cgs checks the git statuses of all git repositories in the
#              current directory.
# Options:     -r	Also check the status of repositories
#                       within the given directories.
# Arguments:   Paths to git repositories to check the status of.

# Unless -r is specified, we only want to look for git repositories at the top
# level of this directory. We use a maxdepth of 2 by default because we are
# `find`-ing the .git directories themselves.
maxdepth="-maxdepth 2"

options="r"
while getopts "$options" o; do
	case "$o" in
		r) maxdepth="" ;;
		*) echo "Usage: cgs [-$options]"; exit ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -eq 0 ]; then
	# Find all directories named .git and take off the '/.git' at
	# the end of each of them to get the paths to the git
	# repositories.
	# (cheers to e36freak of #bash@libera.chat for help with this)

	# There are no quotes around $maxdepth so that "-maxdepth 2" isn't
	# interpreted as a single predicate.
	# shellcheck disable=SC2086
	repos="$(find . $maxdepth -type d -name .git -prune \
		| sed -e 's:/\.git$::' -e 's:^\./::' | sort)"
else
	repos="$*"
fi

for dir in $repos; do

	st="$(git -C "$dir" -c color.status=always status -sb)"

	if [ "$(echo "$st" | wc -l)" -ge 2 ] || echo "$st" | grep -q ']$'; then
		echo "$dir $st"
	fi
done
