#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        display-todo
# Description: Display a formatted to-do file with dunst.


# This is an intended newline here.
str="To-do:
$(awk '{ print NR " " $0 }' ~/TODO)"

pgrep dunst >/dev/null && dunstify "$str" || echo "$str"

