#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        mycmus
# Description: Transmits info of current song playing in cmus using dmenu.

get_value()
{
	echo "$(cmus-remote -C status | grep "^tag $1" | cut -d' ' -f3-)"
}

artist="$(get_value artist)"
album="$(get_value album)"
title="$(get_value title)"

info="$artist - $album - $title"

# If the music is improperly tagged, at least give the file name.
[ "$info" = " - album - " ] && info="$(get_value file)"

# Yank: Pastes song info into system clipboard
# Duck: Opens web browser and searches song info on DuckDuckGo
# Skip: Skips the song, going to next one
# Repeat: Starts the song over from the beginning
case "$(printf "Yank\nDuck\nSkip\nRepeat" | dmenu -i -b -p "$info")" in
	Yank) echo "$info" | xclip -selection c ;;
	Duck) firefox "https://www.duckduckgo.com/$info" ;;
	Skip) cmus-remote -n ;;
	Repeat) cmus-remote -k 0 ;;
esac
