#!/bin/sh
# Copyright (c) 2020-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        cleanvideo
# Description: Filters some background noise from a video; optionally converts
#              the format.

[ "$#" -eq 2 ] && ffmpeg -i "$1" -af "highpass=f=200, lowpass=f=3000" "$2"\
	|| echo "Usage: clean-video in.format out.format"
