#!/bin/sh
# Copyright (c) 2020-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# cleanvideo
#	Filters some background noise from a video.
#	Optionally converts the format.
# Arguments:
#	input file, output file

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 2 ]; then
	echo "$0: invalid arguments provided" >&2
	print_help >&2
	exit 1
fi

ffmpeg -i "$1" -af "highpass=f=200, lowpass=f=3000" "$2"
