#!/bin/sh
# Copyright (c) 2020-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# cleanvideo
#	Filters some background noise from a video.
#	Optionally converts the format.

[ "$#" -eq 2 ] && ffmpeg -i "$1" -af "highpass=f=200, lowpass=f=3000" "$2"\
	|| echo "Usage: clean-video in.format out.format"
