#!/bin/sh
# Copyright (c) 2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# current-twitch-chat
#	Opens the twitch chat of the current stream being watched, if
#	there is one.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: no argument provided" >&2
	print_help >&2
	exit 1
fi

ps ax | awk '
/\/usr\/bin\/streamlink.* twitch.tv\/.* / {
	# The twitch.tv argument is usually after a lot of options when
	# launched by streamlink-twitch-gui, so start looking from the end
	# first.
	for (i = NF; i > 0; i--) {
		if (index($i, "twitch.tv/") == 1) {
			sub(/twitch.tv\//, "", $i)
			system("chatterino -c " $i)
			exit
		}
	}
}'
