#!/bin/sh
# Copyright (c) 2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        dh
# Description: Lists how much disk space each child directory is using.
# Arguments:   (optional) directory to read; reads the current directory by
#              default

du -hd 1 "${1-.}" | sort -h
