#!/bin/sh
# Copyright (c) 2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# dh
#	Lists how much disk space each child directory is using.
# Arguments:
#	The directory to read from.
#	If one is not provided, the current directory is used.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -eq 1 ]; then
	directory="$1"
elif [ "$#" -eq 0 ]; then
	directory='.'
else
	echo "$0: invalid arguments provided" >&2
	print_help >&2
	exit 1
fi

du -hd 1 "${1-.}" | sort -h
