#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        display-todo
# Description: Display a formatted to-do file with dunst.


# This is an intended newline here.
str="To-do:
$(awk '{ print NR " " $0 }' ~/TODO)"

pgrep dunst >/dev/null && dunstify "$str" || echo "$str"

