#!/bin/sh
# Copyright (c) 2021-2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        dl
# Description: Downloads the given URLs.
# Options:     -r        Download the URL recursively using wget. User
#                        discretion is advised.
# Arguments:   URLs to download.

usage()
{
	echo "USAGE: dl [-r] [url]..."
}

while getopts "rh" o; do
	case "$o" in
		r) recurse=1 ;;
		*) usage; exit ;;
	esac
done

shift $((OPTIND - 1))

for file in "$@"; do
	if [ "$recurse" ]; then
		wget -r -l 0 -e robots=off "$file"
	else
		curl -LO "$file"
	fi
done
