#!/bin/sh
# Copyright (c) 2021-2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# dl
#	Downloads the given URLs.
# Options:
#	-r	Download recursively using wget. Be careful with this.
# Arguments:
#	URLs to download.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='hr'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		r) recurse=1 ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -eq 0 ]; then
	echo "$0: no arguments provided" >&2
	print_help >&2
	exit 1
fi

for file in "$@"; do
	if [ "$recurse" ]; then
		wget -r -l 0 -e robots=off "$file"
	else
		curl -LO "$file"
	fi
done
