#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com
# SPDX-License-Identifier: MIT
#
# File:        download
# Description: Downloads the given URLs.
# Options:     -r        Download the URL recursively using wget. User
#                        discretion is advised.
# Arguments:   URLs to download.

usage()
{
	echo "USAGE: download [-r] [url]..."
}

while getopts "rh" o; do
	case "$o" in
		r) recurse=1 ;;
		*) usage; exit ;;
	esac
done

shift $((OPTIND - 1))

for file in "$@"; do
	if [ "$recurse" ]; then
		wget -r -l 0 -e robots=off "$file"
	else
		curl -LO "$file"
	fi
done
