#!/bin/sh
# Copyright (c) 2019-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# intlkey
#	Toggles between the US and US INTL keyboard layouts.
# Options:
#	-i	Instead of toggling the layout, print the active layout.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='hi'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		i) i=1 ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: invalid arguments provided" >&2
	print_help >&2
	exit 1
fi

variant="$(setxkbmap -query | awk '/^variant:/ { print $2 }')"

if [ "$i" ]; then
	if [ "$variant" = "intl" ]; then
		echo 'INTL'
	else
		echo 'US'
	fi
else
	if [ "$variant" = "intl" ]; then
		setxkbmap us
	else
		setxkbmap us -variant intl
	fi
	# Automatically updated dwmblocks status bar. signal 17: 34+17=51
	kill -51 $(pidof dwmblocks)
fi
