#!/bin/sh
# Copyright (c) 2019-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# intlkey
#	Toggles between the US and US INTL keyboard layouts.
# Options:
#	-i	Instead of toggling the layout, print the active layout.

usage()
{
	echo "usage: intlkey [-i]"
}

while getopts "i" o; do
	case "$o" in
		i) i=1 ;;
		*) usage; exit ;;
	esac
done

variant="$(setxkbmap -query | awk '/^variant:/ { print $2 }')"

if [ "$i" ]; then
	if [ "$variant" = "intl" ]; then
		echo 'INTL'
	else
		echo 'US'
	fi
else
	if [ "$variant" = "intl" ]; then
		setxkbmap us
	else
		setxkbmap us -variant intl
	fi
	# Automatically updated dwmblocks status bar. signal 17: 34+17=51
	kill -51 $(pidof dwmblocks)
fi
