#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        intlkey
# Description: Toggles between the US and US INTL keyboard layouts.

if [ "$(setxkbmap -query | grep variant | awk '{print $2}')" = "intl" ]
then
    setxkbmap us
else
    setxkbmap us -variant intl
fi
