#!/bin/sh
# Copyright (c) 2021-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# jdkdocs
#	Prompts the user with dmenu for a file to view from offline
#	JDK documentation.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: invalid arguments provided" >&2
	print_help >&2
	exit 1
fi

docs_location="$HOME/Code/documents/jdk/"
cd "$docs_location" || exit 1

# File names are sorted by their length, so that files with shorter
# names are first, because this way search results are effectively
# sorted by the percentage of the file name that is made up by the
# query.

# In the xargs command, the input is tested first so that firefox will
# open only if a path is provided from dmenu. If instead <ESC> is
# pressed and no file is chosen, then firefox won't open.
# The -r option is not used because it is not portable.

find . -name '*.html' |
	awk '{ print length(), $0 }' |
	sort -n |
	cut -d' ' -f2- |
	dmenu -i -p 'Which file? ' -l 20 |
	xargs -I '{}' sh -c 'test {} && firefox {}'
