#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# lastscreenshot
#	Performs actions on the last screenshots taken. See below.
# Options:
#	-c	cat the last screenshot to stdout.
#	-g	Open the last screenshot in gthumb.
#	-p	Print the path of the last screenshot. (The default)
#	-s	View all screenshots in sxiv, starting from the newest.
# Arguments:
# 	The maximum amount of files to use.
# 	If no arguments are provided, it defaults to 1.

screenshot_path="${SCREENSHOT_DIR:-"$HOME/Documents/pictures/screenshots/"}"
if [ ! -d "$screenshot_path" ]; then
	printf 'lastscreenshot: %s: no such directory\n' "$screenshot_path" >&2
	exit 1
fi

screenshots_time_sorted()
{
	# sed removes a double '//', for if "$screenshot_path" ends with a '/'.

	# It is said not to parse ls in scripts, because of the way it can
	# mangle filenames with weird characters like newlines. I do so here,
	# because I think the risk of running into such characters in this
	# context is small, and because POSIX provides a standard way to sort
	# by time with ls. The best I can do with find is
	#
	#	find . -type f -printf '%T@\t%p\n' | sort -nk1 | cut -f2-
	#
	# and even that depends on the -printf GNUism.
	# shellcheck disable=SC2012
	ls -1At "$screenshot_path"/* | sed 's://:/:g'
}

usage()
{
	echo 'usage: lastscreenshot [-cghps] [amt]' >&2
}

print_path=1
amount=1

options='cghps'
while getopts "$options" o; do
	case "$o" in
		c) unset print_path; cat=1 ;;
		g) unset print_path; gthumb=1 ;;
		p) print_path=1 ;;
		s) unset print_path; sxiv=1 ;;
		*) usage; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$1" ]; then
	if [ "$1" -gt 0 ]; then
		amount="$1"
	else
		echo 'Argument must be an integer greater than zero' >&2
		exit 1
	fi
fi

[ "$print_path" ] && screenshots_time_sorted | sed "$amount"q &
[ "$cat" ] && screenshots_time_sorted | sed "$amount"q | xargs cat &
[ "$gthumb" ] && screenshots_time_sorted | sed "$amount"q | xargs gthumb &
[ "$sxiv" ] && screenshots_time_sorted | sxiv - &

wait
