#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        lastscreenshot
# Description: Opens the last screenshot taken in sxiv, and queues all previous
#              screenshots to be viewed.

# Directory containing the screenshots.
screenshot_path="${SCREENSHOT_DIR:-"$HOME/Documents/pictures/screenshots/"}"

cd "$screenshot_path" || exit

# This is intentional word splitting.
# shellcheck disable=SC2046
sxiv $(ls -A1t)
