#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        lcg
# Description: Launches several instances of catgirl running under tabbed,
#              to facilitate connections to several IRC servers.
# Arguments:   catgirl config files to use.

catgirl_configs="${CATGIRL_DIR:-$XDG_CONFIG_HOME/catgirl/dev}"

[ "$#" -gt 0 ] && servers="$*" \
	|| servers="$(find "$catgirl_configs" -type f)"

window="$(tabbed -d)"

echo "$window"

for file in $servers; do
	st -w "$window" -e catgirl "$file" &
done
