#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        lessdown
# Description: Format the given Markdown file(s) to view in less.
# Arguments:   Markdown files to view

# $ expressions are deliberately unexpanded for use in awk.
# shellcheck disable=SC2016
awkfmt='
/^```/ { codeblock = !codeblock }

# Print non-top-level headings in blue, without indentation
/^##/ { print "\033[;34m" $0 "\033[0m"; next }

# Print top level headings in bold blue, without indentation
/^#/ { print "\033[1;34m" $0 "\033[0m"; next }

# Indent non-heading lines
{ print "\t" $0 }
'

cols="$(tput cols)"
tabwidth="$(infocmp "$TERM" | grep -o 'it#[0-9]*' | tr -dc '0-9')"

fold -sw "$((cols - tabwidth - 2))" "$@" |
	awk -v 'codeblock=0' "$awkfmt" |
	less -R
