#!/bin/sh
# Copyright (c) 2021-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# musicsum
#	Sums the duration of the provided audio files.
# Arguments:
#	Audio files to sum the duration of.

# Recall that there are 3600 seconds in an hour and 60 seconds in a minute.

if [ "$#" -eq 0 ]; then
	mediainfo --Output=JSON ./*
else
	mediainfo --Output=JSON "$@"
fi | jq -r '
	map(.media.track | .[] | select(."@type" == "Audio") | .Duration | tonumber)
		| add
		| (. / 3600 | floor | tostring) + "h"
			+ ((. % 3600) / 60 | floor | tostring) + "m"
			+ (. % 60 | tostring) + "s"
'
