#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        mylight
# Description: Call `light` and notify of the new light level
# Options:     See light(1).

sudo light "$@"
dunstctl close
light | xargs -Ix dunstify -t 500 x
