#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        mylight
# Description: Call `light` and notify of the new light level
# Options:     See light(1).

sudo light "$@"
dunstctl close
light | xargs -Ix dunstify -t 500 x
