#!/bin/sh
# Copyright (c) 2019-2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# mymusic
#	Transmits info of current song playing in mpd using dmenu.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: illegal arguments provided" >&2
	print_help >&2
	exit 1
fi

info="$(mpc -f '%artist% "%album%" (%date%) - %title%' current)"

# Yank: Pastes song info into system clipboard
# Duck: Opens web browser and searches song info on DuckDuckGo
# Skip: Skips the song, going to next one
# Repeat: Starts the song over from the beginning
case "$(printf "Yank\nDuck\nSkip\nRepeat" | dmenu -i -b -p "$info")" in
	Yank) echo "$info" | xclip -selection c ;;
	Duck) firefox "https://www.duckduckgo.com/$info" ;;
	Skip) mpc next ;;
	Repeat) mpc seek 0 ;;
esac
