#!/bin/sh
# Copyright (c) 2019-2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        mymusic
# Description: Transmits info of current song playing in mpd using dmenu.

mpc -f '%artist% - %title% (%album%)' current

# Yank: Pastes song info into system clipboard
# Duck: Opens web browser and searches song info on DuckDuckGo
# Skip: Skips the song, going to next one
# Repeat: Starts the song over from the beginning
case "$(printf "Yank\nDuck\nSkip\nRepeat" | dmenu -i -b -p "$info")" in
	Yank) echo "$info" | xclip -selection c ;;
	Duck) firefox "https://www.duckduckgo.com/$info" ;;
	Skip) mpc next ;;
	Repeat) mpc seek 0 ;;
esac
