#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        mypassmenu
# Description: Opens a stylized dmenu prompt with passwords to select
#              from.

# The directory containing the passwords.
passdir="${PASSWORD_STORE_DIR-~/.password-store}"

find "$passdir" -name '*.gpg' | sed -e "s:^$passdir/::" -e 's/\.gpg$//' | sort |
	dmenu -i -c -fn 20 -sb '#b00' -l 30 |
	xargs pass show -c 2>/dev/null
