#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        new
# Description: Opens a new program, called by the program arguments.

nohup "$@" >/dev/null &
