#!/bin/sh
# Copyright (c) 2020-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        pausemusic
# Description: Toggles music playback, if music is playing in either pianobar
#              or cmus.

pidof cmus && cmus-remote -u
pidof pianobar && printf ' ' > ~/.config/pianobar/ctl
