#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        quitdwm
# Description: Quits dwm, but first prompts the user with a dmenu prompt asking
#              if they are sure.

if [ "$(printf "Y\nN" | dmenu -i -sb 'dark red' -p "Are you sure?")" = "Y" ]
then

	#shellcheck disable=SC2009
	ps --sort -etime x o pid,etime,tty,comm |
		grep ' dwm$' |
		dmenu -n -l 6 -sb 'dark green' -p "Which one?" |
		awk '{ print $1 }' |
		xargs kill
fi
