#!/bin/sh
# Copyright (c) 2023 Sebastian LaVine <mail@smlavine.com>
# Copyright (c) 2019 askUbuntu contributor waltinator
# See <https://askubuntu.com/questions/1124875/how-do-i-set-askpass-variable/1124924#1124924>.
# SPDX-License-Identifier: CC-BY-SA-4.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# reload-keyboard
#	Reloads the wireless USB keyboard.
#	This is useful because there is a bug where keyboard scroll
#	stops working when the keyboard is used after the computer has
#	been asleep.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: illegal arguments provided" >&2
	print_help >&2
	exit 1
fi

# This is based originally on the askUbuntu response linked above.

port="3-3.2" # as shown by lsusb -t: {bus}-{port}(.{subport})

echo "$port" >/sys/bus/usb/drivers/usb/unbind
sleep 0.25
echo "$port" >/sys/bus/usb/drivers/usb/bind
