#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the GPLv3. See GPLv3.txt for details.
#
# File:        rotate-screen
# Description: Provide a dmenu interface to rotate the screen.

run()
{
	way="$(dmenu -c -i -l 5 -fn 'monospace:size=50' -p 'Which way?' |
		tr '[:upper:]' '[:lower:]')"
	case "$way" in
		left)     matrix="0 -1 1 1 0 0 0 0 1"  ;;
		right)    matrix="0 1 0 -1 0 1 0 0 1"  ;;
		inverted) matrix="-1 0 1 0 -1 1 0 0 1" ;;
		normal)   matrix="1 0 0 0 1 0 0 0 1"   ;;
		*)   exit 0 ;;
	esac

	xrandr -o "$way" || exit $?

	# Without this command, the touch screen inputs do not match up with
	# the new orientation of the screen.
	xinput --set-prop 'Wacom ISDv4 E6 Pen Pen (0)' \
		'Coordinate Transformation Matrix' $matrix
}

run << EOF
Left
Right
Inverted
Normal
*Cancel*
EOF
