#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        rs
# Description: Controls the blue light filter.
# Options:     -f        Turn off the blue light filter.
# Options:     -n        Turn on the blue light filter.
# Options:     -t        Toggle the blue light filter. (Assumed)

rs_on="$XDG_DATA_HOME/smlss/rs_on"
[ ! -d "$(dirname "$rs_on")" ] && mkdir -p "$(dirname "$rs_on")"

off()
{
	redshift -x
	rm "$rs_on"
}

on()
{
	redshift -PO 3500
	touch "$rs_on"
}

toggle()
{
	if [ -f "$rs_on" ]; then
		off
	else
		on
	fi
}

options="fnt"
while getopts "$options" o; do
	case "$o" in
		f) off; exit ;;
		n) on; exit ;;
		t) toggle; exit ;;
		*) echo "Usage: rs [-$options]"; exit ;;
	esac
done

# With no options:
toggle
