#!/bin/sh
# Copyright (c) 2021-2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# rs
#	Controls the blue light filter.
# Options:
#	-f	Turn off the blue light filter.
#	-n	Turn on the blue light filter.
#	-t	Toggle the blue light filter. (The default)
# Arguments:
#	If any, display whether or not the filter is active.

rs_on="$XDG_DATA_HOME/smlss/rs_on"
[ ! -d "$(dirname "$rs_on")" ] && mkdir -p "$(dirname "$rs_on")"

off()
{
	redshift -x
	rm "$rs_on"
}

on()
{
	redshift -PO 3500
	touch "$rs_on"
}

toggle()
{
	if [ -f "$rs_on" ]; then
		off
	else
		on
	fi
}

options="fnt"
while getopts "$options" o; do
	case "$o" in
		f) off; exit ;;
		n) on; exit ;;
		t) toggle; exit ;;
		*) echo "Usage: rs [-$options]"; exit ;;
	esac
done

shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	toggle
else
	if [ -f "$rs_on" ]; then
		notify-send -t 3000 "The blue light filter is ON."
	else
		notify-send -t 3000 "The blue light filter is OFF."
	fi
fi
