#!/bin/sh
# Copyright (c) 2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        sb-date
# Description: Prints the date in a format desirable for my status bar. See
#              <https://git.sr.ht/~smlavine/dwmblocks>.

date '+%a %b %d %r %Z'
