#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# shoot
#	Saves a screenshot as PNG. Intended for use with a keybind.
# Options:
#	-d	Prompts for a filename with dmenu instead of using a
#		timestamp.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}


# take picture as soon as possible
file="$(mktemp)"
xwd -root | convert xwd:- png:"$file"

options='dh'
while getopts "$options" o; do
	case "$o" in
		d) name="$(dmenu -p "Name?" < /dev/null)"
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: illegal arguments provided" >&2
	print_help >&2
	exit 1
fi

picture_path="${SCREENSHOT_DIR:-"$HOME/Documents/pictures/screenshots/"}"

# either "-d" not used, OR dmenu cancelled out before input:
# generate name based on time taken
# example: "screenshot2019-11-17.948921698"
[ -z "$name" ] && name="screenshot$(date '+%F.%N')"

if [ -d "$picture_path" ]; then
	mv "$file" "$picture_path/$name.png"
else
	mv "$file" "$HOME/$name.png"
fi
