#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        sxivpipe
# Description: Read in an image from stdin, and view it with sxiv.

file="$(mktemp)"

cat > "$file"  # Read image from stdin

sxiv "$file"

rm "$file"
