#!/bin/sh
# Copyright (c) 2022 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# touch-launch
#	Provide a menu to launch a program.
#	Opens a keyboard to type letters to narrow down search.
#	Works best if dmenu_run is replaced with dmenu_run_history.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	echo "$0: illegal arguments provided" >&2
	print_help >&2
	exit 1
fi

if ! pgrep svkbd-en >/dev/null; then
	svkbd-en &
	pid="$!"
fi

dmenu_run -i -c -y -100 -fn 'monospace:size=25' -sb '#b00' -l 8

if [ "$pid" ]; then
	kill -9 "$pid"
fi
