#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the GPLv3. See GPLv3.txt for details.
#
# File:        touch-menu
# Description: Provide a menu to perform common activites without needing to
#              input commands with a keyboard. This is useful in mouse-only
#              environments, such as when the keyboard is unavailable in a
#              laptop with tablet capabilities like the Thinkpad X220 Tablet.

rotate-screen
