#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        unhibernate
# Description: Temporarily disables laptop hibernation upon closing the laptop
#              lid.

echo Unhibernation begun. Press Ctrl+C to stop.
systemd-inhibit --what=handle-lid-switch cat

