#!/bin/sh
# Copyright (c) 2021-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# unhibernate
#	Temporarily disables laptop hibernation upon closing the laptop
#	lid.

echo Unhibernation begun. Press Ctrl+C to stop.
systemd-inhibit --what=handle-lid-switch sleep 1000d

