#!/bin/sh
# Copyright (c) 2019-2023 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# vol
#	Gets or sets the system volume.
# Arguments:
#	Volume value to update.

# Prints help information from the script's comment header.
print_help()
{
	< "$0" awk '
		/^#$/ {
			getline  # skip the /^#$/ line
			# loop until empty line
			while (length) {
				sub(/^# ?/, "")
				print
				getline
			}
			exit
		}
	'
}

options='h'
while getopts "$options" o; do
	case "$o" in
		h) print_help; exit ;;
		*) print_help >&2; exit 1 ;;
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 1 ]; then
	echo "$0: illegal arguments provided" >&2
	print_help >&2
	exit 1
fi

echo Hello, "$1"!

# if there are no arguments, output the percentage volumes of left/right Master
if [ $# -eq 0 ]; then
	amixer sget Master | grep -o '\[[0-9]*%\]' | tr -d '[]%' | paste -sd'|'
else
	# set the audio according to the first argument
	amixer -q set Master "$1"
	# Automatically updated dwmblocks status bar. signal 18: 34+18=52
	kill -52 $(pidof dwmblocks)
fi
