#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        vol
# Description: Gets or sets the system volume.
# Arguments:   (optional) argument to amixer (ex. 40%, 500, 5%+, 6%-)

# if there are no arguments, output the percentage volumes of left/right Master
if [ $# -eq 0 ]; then
	amixer sget Master | grep -o '\[[0-9]*%\]' | tr -d '[]%' | paste -sd'|'
else
	# set the audio according to the first argument
	amixer -q set Master "$1"
	# Automatically updated dwmblocks status bar. signal 18: 34+18=52
	kill -52 $(pidof dwmblocks)
fi
