#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MIT
#
# File:        xp
# Description: Write stdin to a file, then pass the file to a given command
# Example:     pandoc README.md | xp firefox
# Arguments:   Command to run

if [ "$#" -eq 0 ]; then
	echo "Usage: ... | xp [command [initial-arguments]]"
	exit 1
fi

file="$(mktemp)"

cat > "$file"  # Read file from stdin

"$@" "$file"

# If a firefox window is already open, then it will open the file as a
# tab in that window, returning to this script before it has actually
# read the file. Then it is removed before it is read. For this reason,
# let's wait a few seconds to give it a change to catch up.
sleep 2

rm "$file"
