#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# File:        xp
# Description: Write stdin to a file, then pass the file to a given command
# Example:     pandoc README.md | xp firefox
# Arguments:   Command to run

if [ "$#" -eq 0 ]; then
	echo "Usage: ... | xp [command [initial-arguments]]"
	exit 1
fi

file="$(mktemp)"

cat > "$file"  # Read file from stdin

"$@" "$file"

# If firefox is already running and controlled by another terminal, then
# this invocation of firefox might return before it has time to read the
# file. For this case, let's give firefox a few seconds to catch up.
if [ "$1" = "firefox" ]; then
	sleep 2
fi

rm "$file"
