#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See MIT.txt for details.
#
# File:        xp
# Description: Write stdin to a file, then pass the file to a given command
# Arguments:   Command to run

if [ "$#" -eq 0 ]; then
	echo "Usage: ... | xp [command [initial-arguments]]"
	exit 1
fi

file="$(mktemp)"

cat > "$file"  # Read file from stdin

"$@" "$file"

rm "$file"
